version: '3'
services:
  
  private:
    build: 
      dockerfile: ./docker/private.Dockerfile
      context: .
    ports:
      - 8081:8081
  
  public:
    build: 
      dockerfile: ./docker/public.Dockerfile
      context: .
    ports:
      - 8082:8082
  # postgres:
  #   image: postgres:15
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test:
  #       - CMD-SHELL
  #       - pg_isready -U postgres -d postgres -q
  #     interval: 3s
  #     start_period: 2m0s
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: main

volumes:
  db_data:
