version: '3'
services:
  
  private:
    build: 
      dockerfile: ./docker/private.Dockerfile
      context: .
    volumes:
      - ./packages/private:/app/packages/private
    ports:
      - 8081:8081
  
  public:
    build: 
      dockerfile: ./docker/public.Dockerfile
      context: .
    volumes:
      - ./packages/public:/app/packages/public
    ports:
      - 8082:8082

  cerbos:
    image: ghcr.io/cerbos/cerbos:latest
    command: ["server", "--config=/data/config.yaml"]
    ports:
      - 3592:3592 # grpc
      - 3593:3593 # http
    volumes:
      - ./cerbos:/data

  postgres:
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d postgres -q
      interval: 3s
      start_period: 2m0s
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main

  minio:
    container_name: Minio
    command: server /minio/data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=asdf
      - MINIO_ROOT_PASSWORD=asdfasdf
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data/minio:/minio/data

  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: asdf
      MONGO_INITDB_ROOT_PASSWORD: asdfasdf


